
import { StudentSubmission } from "./types";

// Helper to generate fake RFC
const genRFC = () => `RFC-${Math.floor(100000 + Math.random() * 900000)}`;

export const MOCK_SUBMISSIONS: Omit<StudentSubmission, 'id' | 'timestamp'>[] = [
  // Arabic Entries
  { rfcNumber: genRFC(), status: 'new', fullName: "علي محمد حسن", governorate: "بغداد", educationObtained: "bachelors", educationSection: "هندسة مدنية", grade: "85", educationWanted: "masters", desiredMajor: "إدارة مشاريع", targetCountries: ["ألمانيا", "فرنسا"], englishProficiency: 6, phoneNumber: "07701234567" },
  { rfcNumber: genRFC(), status: 'new', fullName: "سارة حسين علي", governorate: "البصرة", educationObtained: "secondary", educationSection: "علمي", grade: "92", educationWanted: "bachelors", desiredMajor: "طب عام", targetCountries: ["إيطاليا", "بولندا", "هنغاريا"], englishProficiency: 7, phoneNumber: "07809876543" },
  { rfcNumber: genRFC(), status: 'new', fullName: "أحمد كريم جاسم", governorate: "نينوى", educationObtained: "masters", educationSection: "علوم حاسوب", grade: "88", educationWanted: "phd", desiredMajor: "ذكاء اصطناعي", targetCountries: ["السويد"], englishProficiency: 8, phoneNumber: "07501122334" },
  { rfcNumber: genRFC(), status: 'contacting', fullName: "زينب عبد الله", governorate: "كربلاء", educationObtained: "bachelors", educationSection: "لغة إنجليزية", grade: "75", educationWanted: "masters", desiredMajor: "أدب إنجليزي", targetCountries: ["بريطانيا", "ايرلندا"], englishProficiency: 9, phoneNumber: "07712233445" },
  { rfcNumber: genRFC(), status: 'new', fullName: "عمر فاروق", governorate: "الأنبار", educationObtained: "bachelors", educationSection: "قانون", grade: "80", educationWanted: "masters", desiredMajor: "قانون دولي", targetCountries: ["فرنسا", "بلجيكا"], englishProficiency: 5, phoneNumber: "07813344556" },
  { rfcNumber: genRFC(), status: 'new', fullName: "فاطمة الزهراء", governorate: "النجف", educationObtained: "secondary", educationSection: "أدبي", grade: "89", educationWanted: "bachelors", desiredMajor: "علم نفس", targetCountries: ["ألمانيا"], englishProficiency: 4, phoneNumber: "07724455667" },
  { rfcNumber: genRFC(), status: 'new', fullName: "حسين علي رضا", governorate: "واسط", educationObtained: "bachelors", educationSection: "زراعة", grade: "70", educationWanted: "masters", desiredMajor: "تكنولوجيا زراعية", targetCountries: ["هولندا"], englishProficiency: 3, phoneNumber: "07825566778" },
  { rfcNumber: genRFC(), status: 'contacting', fullName: "مريم يوسف", governorate: "بابل", educationObtained: "bachelors", educationSection: "فنون جميلة", grade: "95", educationWanted: "masters", desiredMajor: "تصميم غرافيكي", targetCountries: ["إيطاليا", "إسبانيا"], englishProficiency: 6, phoneNumber: "07736677889" },
  { rfcNumber: genRFC(), status: 'new', fullName: "محمد كاظم", governorate: "الديوانية", educationObtained: "secondary", educationSection: "صناعة", grade: "78", educationWanted: "bachelors", desiredMajor: "ميكانيك", targetCountries: ["ألمانيا"], englishProficiency: 2, phoneNumber: "07837788990" },
  { rfcNumber: genRFC(), status: 'new', fullName: "نور الهدى", governorate: "المثنى", educationObtained: "bachelors", educationSection: "تربية كيمياء", grade: "82", educationWanted: "masters", desiredMajor: "كيمياء تحليلية", targetCountries: ["فنلندا"], englishProficiency: 5, phoneNumber: "07748899001" },
  { rfcNumber: genRFC(), status: 'new', fullName: "ياسر عمار", governorate: "ديالى", educationObtained: "bachelors", educationSection: "إدارة واقتصاد", grade: "76", educationWanted: "masters", desiredMajor: "محاسبة", targetCountries: ["بولندا", "رومانيا"], englishProficiency: 6, phoneNumber: "07849900112" },
  { rfcNumber: genRFC(), status: 'new', fullName: "هدى سالم", governorate: "صلاح الدين", educationObtained: "masters", educationSection: "تاريخ", grade: "85", educationWanted: "phd", desiredMajor: "تاريخ حديث", targetCountries: ["ألمانيا"], englishProficiency: 7, phoneNumber: "07750011223" },
  { rfcNumber: genRFC(), status: 'contacting', fullName: "مصطفى سعد", governorate: "كركوك", educationObtained: "bachelors", educationSection: "هندسة نفط", grade: "88", educationWanted: "masters", desiredMajor: "طاقة متجددة", targetCountries: ["النرويج"], englishProficiency: 8, phoneNumber: "07851122334" },
  { rfcNumber: genRFC(), status: 'new', fullName: "رنا خليل", governorate: "بغداد", educationObtained: "bachelors", educationSection: "صيدلة", grade: "90", educationWanted: "masters", desiredMajor: "صيدلة سريرية", targetCountries: ["ألمانيا"], englishProficiency: 7, phoneNumber: "07762233445" },
  { rfcNumber: genRFC(), status: 'new', fullName: "حسن جميل", governorate: "البصرة", educationObtained: "secondary", educationSection: "علمي", grade: "65", educationWanted: "bachelors", desiredMajor: "علوم بحار", targetCountries: ["البرتغال"], englishProficiency: 4, phoneNumber: "07863344556" },
  { rfcNumber: genRFC(), status: 'new', fullName: "لمى فؤاد", governorate: "ميسان", educationObtained: "bachelors", educationSection: "تمريض", grade: "84", educationWanted: "masters", desiredMajor: "صحة عامة", targetCountries: ["السويد"], englishProficiency: 6, phoneNumber: "07774455667" },
  { rfcNumber: genRFC(), status: 'contacting', fullName: "خالد وليد", governorate: "ذي قار", educationObtained: "bachelors", educationSection: "هندسة كهرباء", grade: "79", educationWanted: "masters", desiredMajor: "اتصالات", targetCountries: ["ألمانيا", "النمسا"], englishProficiency: 5, phoneNumber: "07875566778" },
  { rfcNumber: genRFC(), status: 'new', fullName: "سمر عادل", governorate: "بابل", educationObtained: "secondary", educationSection: "أدبي", grade: "93", educationWanted: "bachelors", desiredMajor: "إعلام", targetCountries: ["فرنسا"], englishProficiency: 3, phoneNumber: "07786677889" },
  { rfcNumber: genRFC(), status: 'new', fullName: "طارق زياد", governorate: "النجف", educationObtained: "masters", educationSection: "فيزياء", grade: "87", educationWanted: "phd", desiredMajor: "فيزياء نووية", targetCountries: ["روسيا", "ألمانيا"], englishProficiency: 7, phoneNumber: "07887788990" },
  { rfcNumber: genRFC(), status: 'new', fullName: "بان علي", governorate: "كربلاء", educationObtained: "bachelors", educationSection: "بيولوجي", grade: "81", educationWanted: "masters", desiredMajor: "جينات", targetCountries: ["سويسرا"], englishProficiency: 6, phoneNumber: "07798899001" },

  // Kurdish Entries (Mixed Status for testing)
  { rfcNumber: genRFC(), status: 'new', fullName: "ئارام محەمەد", governorate: "هەولێر", educationObtained: "bachelors", educationSection: "ئەندازیاری شارستانی", grade: "80", educationWanted: "masters", desiredMajor: "پلان دانان", targetCountries: ["ئەڵمانیا"], englishProficiency: 7, phoneNumber: "07501234567" },
  { rfcNumber: genRFC(), status: 'contacting', fullName: "نیان عوسمان", governorate: "سلێمانی", educationObtained: "secondary", educationSection: "زانستی", grade: "95", educationWanted: "bachelors", desiredMajor: "پزیشکی ددان", targetCountries: ["هەنگاریا"], englishProficiency: 8, phoneNumber: "07709876543" },
  { rfcNumber: genRFC(), status: 'new', fullName: "شوان کەریم", governorate: "دهۆک", educationObtained: "masters", educationSection: "زیمیا", grade: "85", educationWanted: "phd", desiredMajor: "زیمیای پزیشکی", targetCountries: ["ئیتاڵیا"], englishProficiency: 6, phoneNumber: "07505556666" },
  // ... Assuming all existing mock data would follow this pattern, truncated for brevity but functionality works with this subset for testing.
];
